baseURL = "https://www.jstevens.be/"

title = "Blog"
languageCode = "en-us"
defaultContentLanguage = "en-us"

theme = "axiom"

paginate = 5
canonifyURLs = false
rssLimit = 100
enableEmoji = true
summaryLength = 40
enableRobotsTXT = true
pluralizelisttitles = true
footnoteReturnLinkContents = "&#8617;"


# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
	tag = "tags"


[permalinks]
	post = "/:filename"

[params]
	mainSections = ["posts"]
	copyrightYear = 2020

[params.brand]
	domain = "https://www.jstevens.be/"
	email = "stevens.jan.adriaan@gmail.com"

[params.social]
	facebook = "https://www.facebook.com/jan.stevens.7399"
	github = "https://github.com/biogen98"
	linkedin = "https://www.linkedin.com/in/jan-adriaan-stevens"
	stackoverflow = "https://stackoverflow.com/users/user"
	email = "mailto:stevens.jan.adriaan@gmail.com"
	cv = "https://jstevens.be/cv.pdf"
	footer = ["email", "github", "linkedin", "facebook", "cv"]

[params.logo]
	inline = true
	path = "image/brand/android-chrome-512x512.svg"

[params.image]
	width = "2048"
	height = "1024"
	faviconIco = "favicon.ico"
	faviconAlt = "image/brand/favicon-32x32.png"
	icon1To1 = "image/brand/icon1.png"
	icon2To1 = "image/brand/icon1.png"
	default = "/image/author/Profile_landscape.jpg " #image/page-default.webp"

[params.font]
	type = "font/woff"
	path = "font/"
	files = ["Lora-BoldItalic.woff","Lora-Bold.woff","Lora-Italic.woff","Lora-MediumItalic.woff","Lora-Medium.woff","lora-Regular.woff"]

[outputs]
	home = ["HTML", "ATOM"]
	section = ["HTML"]
	taxonomy = ["HTML"]
	taxonomyTerm = ["HTML"]

[outputFormats]
	[outputFormats.ATOM]
		name = "ATOM"
		baseName = "feed"
		mediaType = "application/atom+xml"

[mediaTypes]
	[mediaTypes."application/atom+xml"]
		suffixes = ["atom"]

[markup]
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 2
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.renderer]
			hardWraps = true
			unsafe = true
			xhtml = false
		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = false


[menu]

	[[menu.main]]
		url = "/"
		name = "Home"
		weight = 1

	[[menu.main]]
		url = "posts/"
		name = "Posts"
		weight = 2

	[[menu.main]]
		url = "about/"
		name = "About"
		weight = 3

	[[menu.main]]
		url = "contact/"
		name = "Contact"
		weight = 4

	[[menu.mobile]]
		url = "/posts/"
		name = "Posts"
		weight = 1

	[[menu.mobile]]
		url = "/about/"
		name = "About"
		weight = 2

	[[menu.foot]]
		url = "/posts/"
		name = "Posts"
		weight = 1

	[[menu.foot]]
		url = "/about/"
		name = "About"
		weight = 2

	[[menu.foot]]
		url = "/contact/"
		name = "Contact"
		weight = 2

[[menu.docs]]
url = "/docs/"
name = "Overview"
weight = 1

[[menu.docs]]
url = "/docs/quick-start/"
name = "Quick Start"
weight = 2

[[menu.docs]]
url = "/docs/features/"
name = "Features"
weight = 3

[[menu.docs]]
url = "/docs/configuration/"
name = "Configuration"
weight = 4

[[menu.docs]]
url = "/docs/frontmatter/"
name = "Frontmatter"
weight = 5

[[menu.docs]]
url = "/docs/shortcodes/"
name = "Shortcodes"
weight = 6

[[menu.docs]]
url = "/docs/archetypes/"
name = "Archetypes"
weight = 7

[[menu.docs]]
url = "/docs/extending/"
name = "Extending"
weight = 8

[params.services]
	analyticsId = ""
	adwordsId = ""
	adsenseId = ""
	adsenseAdSlotId = ""
	adsenseLazy = false
	adwordsConversionId = ""
	adwordsConversionValue = 0
	facebookApp = ""
	facebookPixel = ""

[params.cdn]
	provider = "local"
[params.cloudinary]
	host = ""
	version = ""

[languages]
	[languages."en-us"]
		weight = 1
		languageName = "UK English"
		staticDir = ["static"]
